[project]
name = "cloudfile"
version = "0.1.0"
description = ""
authors = [
    {name = "CloudberryPiTech",email = "bubblesbakale1@outlook.com"}
]
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "encoding @ git+https://github.com/cloudberrypitech/encoding",
    "black (>=26.5.1,<27.0.0)"
]

[tool.poetry]
packages = [{include = "cloudfile", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
